### ISSUE TITLE
Issue in assert(lpr_per_codon[thread_id].size() * 3 <= bls_per_bp[thread_id].size());

### ISSUE THREAD

**Issue by pskvins** [cpockrandt/PhyloCSFpp#5]
Hi,
I was trying to run PhyloCSF++ with build-tracks command, and I'm having issue with it so I want you to see what would be the problem with it.

First of all, the command I used for the system was
build-tracks 
--threads 8
--output-phylo 1 
--genome-length 23513712 
--coding-exons codingexon_for_drosophila.txt 
23flies 
chr2L.maf

For the maf, fasta, and off file, I used the chr2L.maf.gz, dm6.fa.gz, dm6.ncbiRefSeq.gtf.gz file from UCSC which you can find from 
[https://hgdownload.soe.ucsc.edu/goldenPath/dm6/multiz27way/maf/](url)
[https://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/](url)
[https://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/genes/](url) respectively,
and I made the codingexon_for_drosophila.txt with the command you `provided(awk -F'\t' 'BEGIN { OFS="\t" } ($3 == "CDS") { print $1, $7, $8, $4, $5 }'`).

When I tried to run the program with the command above, it always stopped at the 152th line of phylocsf++build_tracks.hpp, which says `assert(lpr_per_codon[thread_id].size() * 3 <= bls_per_bp[thread_id].size());`.

For the value of lpr_per_codon and bus_per_bp, I got the value as below.
(lldb) p lpr_per_codon[thread_id].size() * 3
(unsigned long) $2 = 43596
(lldb) p bls_per_bp[thread_id].size()
(vector<double, allocator<double> >::size_type) $4 = 5207

I also tried to run the program with other man files which I just cut some informations from chr2L.maf file, such informations that are about triCas2, musDom2, apiMel4, anoGam1 species which are not in the 23flies model, or alignments that is not aligned with any other species, which is just giving sequence of one species with score=0, and I got exactly same error from these cases too.

I also tried to run the program with making the command --threads 1 and with the pruned files, but it also made the same error as well.

If you need any more informations about the issue, please leave comments below, then I will answer as soon as possible.

Thank you.

**Comment by cpockrandt** [comment]
Hello @pskvins,

thanks for checking out PhyloCSF++. You found a misplaced `assert()` that was unfortunately not caught by the test-cases. I fixed it on the master-branch.

On an unrelated note: when passing the genome size to `build-tracks`, you should pass the overall genome size, even if you only score a single chromosome (the genome size is used together with the coding coordinates to compute things like the ratio of coding/non-coding regions).

In your case where you only score a single chromosome with an MSA that does not have any or very few gaps (i.e., no aligned sequences to the reference), there won't be much parallelization going on. Currently the whole-genome MSA is split into chromosomes and gap-free sub-alignments over which PhyloCSF++ is parallelizing. An improvement for this is in the making.

If there are any other questions, feel free to (re-)open this or another ticket. :)
